### ISSUE TITLE
Code review of Tweet Generator Submission 1

### ISSUE THREAD

**Issue by SWHarrison** [tempor1s/tweetgen#1]
1. dictionary_words works well and is optimized for run time. Try adding benchmarking to see if there are alternative ways to choose random words. One possibility is to randomly select words as you are reading in to avoid going through the list an additional time.
2. All types of histogram work as intended. I recommend adding benchmarking not only for creating the different types of histograms, but also for sampling them. While it might be fastest to create a dictionary histogram, sampling can be faster for other types. Also, your list of counts utilized the dictionary histogram in it's creation. While reusing code is generally good practice, it defeats the purpose of the exercise to attempt other solutions. I encourage you to try to find a solution that does not utilize your other histogram functions.
3. Sampling function works as expected. I encourage you to try it with the list of counts histogram and compare it's run time to the others.
4. Heroku app is live and looks great, nice job!
5. Markov chain works as expected. Try the stretch challenge of including start and stop tokens!

**Comment by tempor1s** [comment]
Thanks! :)

**Comment by tempor1s** [comment]
Uses start and stop tokens. 🙌
