### ISSUE TITLE
Code Review of Hashtables

### ISSUE THREAD

**Issue by SWHarrison** [tempor1s/tweetgen#3]
- Great job adding additional tests to check the robustness of your code! One thing to note is that python's hashing function uses the time of day for it's calculation, so it is important to test any code that uses ```hash``` multiple times to make sure it works whether there are collisions or not, something to keep in mind!
- Good work adding functions to make your hash table more useable, a great next step is adding methods such as ```__getitem__``` to allow your hash table to be used like python's dictionary.
- Excellent comments, keep up the good work!
- In your clear method, you go through and manually delete every key in the hash table. Unless you are worried about pointers from previously "deleted" nodes sticking around, it can be much faster to simply create a new linked list for each bucket, as that will always take O(b) time rather than depend on the number of entries. As such it might be worth checking the size and then either deleting each entry or recreating a new linked list for each bucket.

**Comment by tempor1s** [comment]
Thanks! I really like the implementation of delete, going to implement it :)

**Comment by tempor1s** [comment]
https://github.com/tempor1s/tweetgen/commit/c07369c06d5ceee44bd3639ffdb209d53844a147 Fast boi clean function.
