### ISSUE TITLE
Final Project Submission Review

### ISSUE THREAD

**Issue by SWHarrison** [tempor1s/tweetgen#4]
- All tests pass and sampling works as expected.
- Some buttons on heroku app appear non-functional. I recommend removing those or adding functionality so users do not think your site is non-functional.
- Great job implementing 2nd order markov chains!
- Here is one possible way to refactor your ```_create_chain```method to be n-th order rather than just 2nd:
```def _create_chain(self, word_list):
        n_words = len(word_list)
        for i, key1 in enumerate(word_list):
            if n_words > (i + self.order): # TODO: use order
                key2 = word_list[i + 1]
                word = word_list[i + 2]
                words = []
                for j in range(self.order):
                    words.append(word_list[i + j])

                entry = tuple(words)
                print(entry)
                if entry not in self:
                    self[entry] = [word]
                else:
                    self[entry].append(word)
```

I encourage you to think of how you can modify your ```walk``` method to work with any order as well.

**Comment by tempor1s** [comment]
Thank you!

**Comment by tempor1s** [comment]
I know you probably don't care, but I rewrote the Markov Chain and it works really well now. Fully n'th order as well as using start and stop tokens.
